#!/bin/sh

BUILD_DEPS="$(perl -ne 'next if /^#/; $p=(s/^Build-Depends:\s*/ / or (/^ / and $p)); s/,|\n|\([^)]+\)//mg; print if $p' < debian/control)"

cat <<EOF > Dockerfile
FROM debian
RUN apt-get update && apt-get install -y crossbuild-essential-armhf $BUILD_DEPS
RUN apt-get -a armhf install -y  $BUILD_DEPS
CMD ['make']
EOF
